services:
  - type: web
    name: 8bit-softworks
    runtime: static
    repo: https://github.com/8bitsoftworks-ship-it/8bitsoftworks-bd
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
